import Head from "next/head";
import Link from "next/link";
import Header from "~/components/layout/Header";
import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#7aa19c] to-[#537a7a]">
        <Header />
      </main>
    </>
  );
}
